- iptables: chain=INPUT jump=DROP

- iptables: chain=INPUT  ctstate='ESTABLISHED,RELATED' jump=ACCEPT
  become: yes

- iptables: chain=INPUT protocol=tcp destination_port=22 ctstate=NEW  jump=ACCEPT
- iptables: chain=INPUT in_interface=lo jump=ACCEPT
- iptables: chain=OUTPUT out_interface=lo  jump=ACCEPT
- iptables: chain=INPUT protocol=80 jump=ACCEPT
- iptables: chain=INPUT protocol=icmp jump=ACCEPT
- name: save iptable rules
  shell:   netfilter-persistent save
  ignore_errors: True
- name: Set restart to reload
  shell:  netfilter-persistent save
  ignore_errors: True
